# The language of all messages in this plugin.
# See the 'lang' folder for all available languages.
default-language: English (United Kingdom)

# Allows players to give themselves (and others) freeze wands.
give-freeze-wand-permission: freeze-wand.give

# Grants players immunity from being frozen.
immune-to-freeze-permission: freeze-wand.immune
